#!/usr/bin/env bash
# Install nginx on your web-01 and should be listening on port 80

sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
sudo ufw allow "Nginx HTTP"
sudo chown -R "$USER":$"USER" /var/www/html/index.nginx-debian.html
sudo chmod -R 755 /var/www
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp
echo -e "Hello World!" | dd status=none of= /var/www/html/index.nginx-debian.html
sudo service nginx restart
