#!/usr/bin/env bash
# configure web-02 to be identical to web-01
# The name of the custom HTTP header must be X-Served-By
# The value of the custom HTTP header must be the hostname of the server Nginx is running on

# Update package lists
apt-get update

# Install Nginx
apt-get install -y nginx

# Get the hostname
hostname=$(hostname)

# Configure Nginx to add custom HTTP header
cat <<EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    location / {
        root /var/www/html;
        index index.html index.htm;
        add_header X-Served-By $hostname;
    }
}
EOF

# Restart Nginx to apply changes
systemctl restart nginx
